# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_auto_20160722_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
