# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_delete_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=300)),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
