# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_event_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
